#pragma once

void Test_Solar();
void Test_Shelly();
void Test_FritzBox();
void Test_Tuya();
void Test_Midea();
void Test_DoorBird();
void Test_XSense();
void Test_Dyson();
void Test_Solarman();
void Test_TuyaDirect();
void Test_MideaDirect();
void Test_FritzBoxDirect();
void Test_SunCalc();
void Test_ScheduleRunner();
void Test_RecordingManager();
void Test_TalkManager();
void Test_AudioSessionManager();